Update db_layout.md
mixayloff-dimaaylov/ionosphere_iif pull request #2
Opened 2020-07-23 21:32 UTC by ioaznnis

2020-07-23 21:38 UTC, mixayloff-dimaaylov commented on docs/specs/database_layout/db_layout.md
> -
Почему эти таблицы удалены?

2020-07-23 21:40 UTC, ioaznnis commented on docs/specs/database_layout/db_layout.md
> -
Они не используются в Spark больше

2020-07-23 21:45 UTC, mixayloff-dimaaylov commented on docs/specs/database_layout/db_layout.md
> -
А куда они переехали?

2020-07-27 16:37 UTC, ioaznnis commented on docs/specs/database_layout/db_layout.md
> -
Если судить по https://github.com/ioaznnis/ionosphere/blob/master/src/main/scala/com/infocom/examples/spark/TecCalculation.scala
То они не используются.

computed.tecsigma -> computed.xz1
computed.tecFiltered -> computed.NTDerivatives
computed.tec -> computed.NT

2020-07-27 16:49 UTC, mixayloff-dimaaylov commented on docs/specs/database_layout/db_layout.md
> -
Остались старые, названия. Вижу, что появились поля f1, f2.

2020-07-27 16:51 UTC, mixayloff-dimaaylov requested changes
Но **COMMENT** не хотелось бы сейчас принимать, по крайней мере до финального состояния.
Нельзя будет просто скопировать и вставить запрос в `clickhouse-client`.

2020-07-27 16:58 UTC, ioaznnis reviewed
> Но **COMMENT** не хотелось бы сейчас принимать, по крайней мере до финального состояния.
> Нельзя будет просто скопировать и вставить запрос в `clickhouse-client`.

Не согласен. С ним прекрасно таблицы создаются

2020-07-27 16:58 UTC, ioaznnis commented on docs/specs/database_layout/db_layout.md
> -  freq Float64,
Вот тут типы не сходятся

2020-07-27 17:00 UTC, mixayloff-dimaaylov commented on docs/specs/database_layout/db_layout.md
> -  freq Float64,
offtopic, учту

2020-07-27 17:03 UTC, mixayloff-dimaaylov commented
Жаль что эти комментарии не во всех таблицах.

2020-07-27 17:15 UTC, merged